### PR TITLE
Fix memory leaks detected by valgrind

### LINKED ISSUE #83: Implement ssl handshake over check
In dtlc_connection_api.c:
```
if (gnutls_session_get_desc(conn->session) == NULL)
{
   ...
}
```
is used to check if handshake is over, but the function allocates new resources. This is done every time a packet is received. GNUTLS does not seem to have a function to check if session is initiated, so we should provide a method to do so.

### PR DESCRIPTION
**Pull request by Lycopersicum**
Closes #83. Requires wakaama leaks fix (https://github.com/punica/wakaama/pull/13).

### CODE REVIEW

File: src/dtls_connection_api.c [hunk 1]
```diff
@@ -632,7 +634,8 @@ static int dtls_connection_receive(void *context_p, uint8_t *buffer, size_t size
 
             if (conn != NULL)
             {
-                if (gnutls_session_get_desc(conn->session) == NULL)
+                session_desc = gnutls_session_get_desc(conn->session);
```
Comment (taubel) [inline src/dtls_connection_api.c]: Need to address #83

Comment (taubel) [reply src/dtls_connection_api.c]: @Lycopersicum Marked this as unresolved because #83 is not fixed
