### PR TITLE
Fix unable to handle multiple clients at once bug

### LINKED ISSUE #62: DTLS server not able to handle multiple client connections at the same time
Happens when multiple clients are trying to establish a DTLS connection at the same time. Some of the client messages are not picked up by the server, forcing the clients to retransmit which causes delays.

### PR DESCRIPTION
**Pull request by taubel**
Closes #62

### CODE REVIEW

**Comment by taubel** [comment]
Should be merged after #60

File: src/dtls_connection_api.c [hunk 1]
```diff
@@ -195,6 +195,74 @@ static ssize_t dtls_connection_net_send(gnutls_transport_ptr_t context, const vo
...
+    ret = select(conn->sock + 1, &fd, NULL, NULL, &tv);
+    if (ret <= 0)
+    {
+        return ret;
+    }
+
+    buffer_length = sizeof(buffer);
+    addr_size = sizeof(addr);
+
+    ret = recvfrom(conn->sock, buffer, buffer_length, MSG_PEEK, &addr, &addr_size);
```
Comment (GiedriusM) [inline src/dtls_connection_api.c]: Isn't this the same as `dtls_connection_net_recv`? If it is, it could be replaced with `return dtls_connection_net_recv(...);`

File: src/dtls_connection_api.c [hunk 2]
```diff
@@ -446,159 +519,165 @@ static int dtls_connection_start(void *context_p)
...
-                    context->conn_listen = conn;
-                    goto connect_fail;
+                    gnutls_dtls_cookie_send(&context->cookie_key, &context->conn_listen->addr,
+                                            sizeof(context->conn_listen->addr), &prestate, context->conn_listen, dtls_connection_net_send);
+                    recvfrom(sock, buffer, size, 0, NULL, NULL);
                 }
-
-//              the current socket will be taken over by the client connection
-                if (connect(conn->sock, (struct sockaddr *)&conn->addr, sizeof(conn->addr)))
+                else if (ret == 0)
```
Comment (GiedriusM) [inline src/dtls_connection_api.c]: Since return code comes from another library it would be better to use it's definition, i.e. `GNUTLS_E_SUCCESS`

File: src/dtls_connection_api.c [hunk 3]
```diff
@@ -622,7 +701,7 @@ static int dtls_connection_close(void *context_p, void *connection)
     {
         do
         {
-            ret = gnutls_bye(conn->session, GNUTLS_SHUT_RDWR);
```
Comment (GiedriusM) [inline src/dtls_connection_api.c]: What's the reason behind this change?

File: src/dtls_connection_api.c [hunk 4]
```diff
@@ -446,159 +519,165 @@ static int dtls_connection_start(void *context_p)
...
-        }
+        return NULL;
     }
 
-    FD_SET(sock, &read_fds);
-    if (sock >= nfds)
-    {
-        nfds = sock + 1;
-    }
+    memcpy(conn, context->conn_listen, sizeof(device_connection_t));
```
Comment (GiedriusM) [inline src/dtls_connection_api.c]: As far as I understand, things like SSL session and user object (`device_identifier`) should not be copied into a new connection, i.e this should not be a clone operation. In any case "blind" object copy is discouraged and either a dedicated function should be used (which indicates soft or hard cloning), or what's likely more appropriate here is just to set the required fields (sock, addr).
